# ---------------------------------------------------------------------------------------------------
# General
# ---------------------------------------------------------------------------------------------------
spring.application.name=administrativeHierarchies-service
application-description=@project.description@
application-version=@project.version@
spring.profiles.active=prod
server.port=8080

# ---------------------------------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------------------------------
database.name=${dbName:administrativeHierarchies}
database.host=${dbHost:localhost}
database.port=${dbPort:5432}
database.username=postgres
database.password=postgres
# Threshold for the estimated Postgres computational units required to finish the query and return results
database.data.request.cost.threshold=100

# ---------------------------------------------------------------------------------------------------
# Security
# ---------------------------------------------------------------------------------------------------
# app.auth-server.host=http://localhost:8400

# ---------------------------------------------------------------------------------------------------
# API
# ---------------------------------------------------------------------------------------------------
# See: https://springdoc.org/#properties
springdoc.swagger-ui.path=/api/v1/administrative_hierarchies/endpoints.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api/v1/administrative_hierarchies/api-docs
springdoc.api-docs.enabled=true

# ---------------------------------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------------------------------
#Levels
logging.level=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.ke.co.miles=TRACE
# Patterns
logging.pattern.console="%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
logging.pattern.file="%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# ---------------------------------------------------------------------------------------------------
# Management
# ---------------------------------------------------------------------------------------------------
# See: https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html
management.endpoints.web.exposure.include=*
management.endpoint.shutdown.enabled=true
